PST.SkillTreesAPI.AddCharacterTree("global", [[
{
"2": "{\"pos\":[0,-2],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[3,315]}",
"3": "{\"pos\":[0,-3],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[2,10,283]}",
"10": "{\"pos\":[0,-4],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[3,11]}",
"11": "{\"pos\":[0,-5],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[10,12,18]}",
"12": "{\"pos\":[1,-5],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[11,13]}",
"13": "{\"pos\":[2,-5],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[12,14]}",
"14": "{\"pos\":[3,-5],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[13,15]}",
"15": "{\"pos\":[3,-6],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[14,16]}",
"16": "{\"pos\":[3,-7],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[15,17]}",
"17": "{\"pos\":[4,-7],\"type\":1,\"size\":\"Med\",\"name\":\"XP gain\",\"description\":[\"+7% XP gain\"],\"modifiers\":{\"xpgain\":7},\"adjacent\":[16,349,350,352]}",
"18": "{\"pos\":[0,-6],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[11,19,24]}",
"19": "{\"pos\":[-1,-6],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[18,20]}",
"20": "{\"pos\":[-2,-6],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[19,21]}",
"21": "{\"pos\":[-3,-6],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[20,28,29,36]}",
"24": "{\"pos\":[0,-7],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[18,25]}",
"25": "{\"pos\":[0,-8],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[24,26,300]}",
"26": "{\"pos\":[0,-9],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[25,27]}",
"27": "{\"pos\":[0,-10],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[26,62,52,42]}",
"28": "{\"pos\":[-5,-6],\"type\":10,\"size\":\"Large\",\"name\":\"Quick Wit\",\"description\":[\"+15% XP earned for the first 8 seconds upon entering a room.\",\"Afterwards, this bonus gradually lowers down to -20% over 10 seconds.\",\"Does not apply in boss rooms.\"],\"modifiers\":{\"quickWit\":[15,-20]},\"adjacent\":[21]}",
"29": "{\"pos\":[-4,-5],\"type\":2,\"size\":\"Small\",\"name\":\"Secret XP\",\"description\":[\"Gain 30 XP upon first entering a secret or\",\"super secret room.\"],\"modifiers\":{\"secretXP\":30},\"adjacent\":[21,30]}",
"30": "{\"pos\":[-4,-4],\"type\":2,\"size\":\"Small\",\"name\":\"Secret XP\",\"description\":[\"Gain 30 XP upon first entering a secret or\",\"super secret room.\"],\"modifiers\":{\"secretXP\":30},\"adjacent\":[29,31]}",
"31": "{\"pos\":[-5,-4],\"type\":2,\"size\":\"Small\",\"name\":\"Secret XP\",\"description\":[\"Gain 30 XP upon first entering a secret or\",\"super secret room.\"],\"modifiers\":{\"secretXP\":30},\"adjacent\":[30,32]}",
"32": "{\"pos\":[-6,-4],\"type\":2,\"size\":\"Small\",\"name\":\"Secret XP\",\"description\":[\"Gain 30 XP upon first entering a secret or\",\"super secret room.\"],\"modifiers\":{\"secretXP\":30},\"adjacent\":[31,33]}",
"33": "{\"pos\":[-7,-4],\"type\":2,\"size\":\"Small\",\"name\":\"Secret XP\",\"description\":[\"Gain 30 XP upon first entering a secret or\",\"super secret room.\"],\"modifiers\":{\"secretXP\":30},\"adjacent\":[32,34]}",
"34": "{\"pos\":[-7,-5],\"type\":17,\"size\":\"Med\",\"name\":\"Secret XP\",\"description\":[\"Gain 100 XP upon first entering a secret or\",\"super secret room.\"],\"modifiers\":{\"secretXP\":100},\"adjacent\":[33,35]}",
"35": "{\"pos\":[-8,-5],\"type\":18,\"size\":\"Large\",\"name\":\"Expert Spelunker\",\"description\":[\"Gain no XP when first entering a secret room.\",\"Gain 350 XP when first entering a super secret room.\"],\"modifiers\":{\"expertSpelunker\":350},\"adjacent\":[34]}",
"36": "{\"pos\":[-4,-7],\"type\":4,\"size\":\"Small\",\"name\":\"Challenge XP\",\"description\":[\"Gain 30 XP upon completing a challenge room round.\"],\"modifiers\":{\"challengeXP\":30},\"adjacent\":[21,37]}",
"37": "{\"pos\":[-4,-8],\"type\":4,\"size\":\"Small\",\"name\":\"Challenge XP\",\"description\":[\"Gain 30 XP upon completing a challenge room round.\"],\"modifiers\":{\"challengeXP\":30},\"adjacent\":[36,38]}",
"38": "{\"pos\":[-5,-8],\"type\":4,\"size\":\"Small\",\"name\":\"Challenge XP\",\"description\":[\"Gain 30 XP upon completing a challenge room round.\"],\"modifiers\":{\"challengeXP\":30},\"adjacent\":[37,39]}",
"39": "{\"pos\":[-6,-8],\"type\":4,\"size\":\"Small\",\"name\":\"Challenge XP\",\"description\":[\"Gain 30 XP upon completing a challenge room round.\"],\"modifiers\":{\"challengeXP\":30},\"adjacent\":[38,40]}",
"40": "{\"pos\":[-7,-8],\"type\":4,\"size\":\"Small\",\"name\":\"Challenge XP\",\"description\":[\"Gain 30 XP upon completing a challenge room round.\"],\"modifiers\":{\"challengeXP\":30},\"adjacent\":[39,41]}",
"41": "{\"pos\":[-7,-7],\"type\":5,\"size\":\"Med\",\"name\":\"Challenge XP\",\"description\":[\"Gain 70 XP upon completing a challenge room round.\",\"+10% XP gain in challenge rooms.\"],\"modifiers\":{\"challengeXP\":70,\"challengeXPgain\":10},\"adjacent\":[40,282]}",
"42": "{\"pos\":[1,-10],\"type\":14,\"size\":\"Small\",\"name\":\"Monster XP\",\"description\":[\"+4% XP from slain normal monsters.\"],\"modifiers\":{\"xpgainNormalMob\":4},\"adjacent\":[27,43]}",
"43": "{\"pos\":[2,-10],\"type\":14,\"size\":\"Small\",\"name\":\"Monster XP\",\"description\":[\"+4% XP from slain normal monsters.\"],\"modifiers\":{\"xpgainNormalMob\":4},\"adjacent\":[42,44]}",
"44": "{\"pos\":[3,-10],\"type\":14,\"size\":\"Small\",\"name\":\"Monster XP\",\"description\":[\"+4% XP from slain normal monsters.\"],\"modifiers\":{\"xpgainNormalMob\":4},\"adjacent\":[43,45]}",
"45": "{\"pos\":[3,-11],\"type\":14,\"size\":\"Small\",\"name\":\"Monster XP\",\"description\":[\"+4% XP from slain normal monsters.\"],\"modifiers\":{\"xpgainNormalMob\":4},\"adjacent\":[44,46]}",
"46": "{\"pos\":[3,-12],\"type\":14,\"size\":\"Small\",\"name\":\"Monster XP\",\"description\":[\"+4% XP from slain normal monsters.\"],\"modifiers\":{\"xpgainNormalMob\":4},\"adjacent\":[45,50,47]}",
"47": "{\"pos\":[3,-13],\"type\":14,\"size\":\"Small\",\"name\":\"Monster XP\",\"description\":[\"+4% XP from slain normal monsters.\"],\"modifiers\":{\"xpgainNormalMob\":4},\"adjacent\":[46,48]}",
"48": "{\"pos\":[3,-14],\"type\":14,\"size\":\"Small\",\"name\":\"Monster XP\",\"description\":[\"+4% XP from slain normal monsters.\"],\"modifiers\":{\"xpgainNormalMob\":4},\"adjacent\":[47,49]}",
"49": "{\"pos\":[2,-14],\"type\":14,\"size\":\"Small\",\"name\":\"Monster XP\",\"description\":[\"+4% XP from slain normal monsters.\"],\"modifiers\":{\"xpgainNormalMob\":4},\"adjacent\":[48,51]}",
"50": "{\"pos\":[4,-12],\"type\":15,\"size\":\"Med\",\"name\":\"Monster XP\",\"description\":[\"+10% XP from slain normal monsters.\"],\"modifiers\":{\"xpgainNormalMob\":10},\"adjacent\":[46]}",
"51": "{\"pos\":[2,-15],\"type\":16,\"size\":\"Large\",\"name\":\"Swarm Challenger\",\"description\":[\"+25% XP from slain normal monsters.\",\"-15% XP from slain bosses.\"],\"modifiers\":{\"xpgainNormalMob\":25,\"xpgainBoss\":-15},\"adjacent\":[49]}",
"52": "{\"pos\":[-1,-10],\"type\":11,\"size\":\"Small\",\"name\":\"Boss XP\",\"description\":[\"+4% XP from slain bosses.\"],\"modifiers\":{\"xpgainBoss\":4},\"adjacent\":[27,53]}",
"53": "{\"pos\":[-2,-10],\"type\":11,\"size\":\"Small\",\"name\":\"Boss XP\",\"description\":[\"+4% XP from slain bosses.\"],\"modifiers\":{\"xpgainBoss\":4},\"adjacent\":[52,54]}",
"54": "{\"pos\":[-3,-10],\"type\":11,\"size\":\"Small\",\"name\":\"Boss XP\",\"description\":[\"+4% XP from slain bosses.\"],\"modifiers\":{\"xpgainBoss\":4},\"adjacent\":[53,55]}",
"55": "{\"pos\":[-3,-11],\"type\":11,\"size\":\"Small\",\"name\":\"Boss XP\",\"description\":[\"+4% XP from slain bosses.\"],\"modifiers\":{\"xpgainBoss\":4},\"adjacent\":[54,56]}",
"56": "{\"pos\":[-3,-12],\"type\":11,\"size\":\"Small\",\"name\":\"Boss XP\",\"description\":[\"+4% XP from slain bosses.\"],\"modifiers\":{\"xpgainBoss\":4},\"adjacent\":[55,60,57]}",
"57": "{\"pos\":[-3,-13],\"type\":11,\"size\":\"Small\",\"name\":\"Boss XP\",\"description\":[\"+4% XP from slain bosses.\"],\"modifiers\":{\"xpgainBoss\":4},\"adjacent\":[56,58]}",
"58": "{\"pos\":[-3,-14],\"type\":11,\"size\":\"Small\",\"name\":\"Boss XP\",\"description\":[\"+4% XP from slain bosses.\"],\"modifiers\":{\"xpgainBoss\":4},\"adjacent\":[57,59]}",
"59": "{\"pos\":[-2,-14],\"type\":11,\"size\":\"Small\",\"name\":\"Boss XP\",\"description\":[\"+4% XP from slain bosses.\"],\"modifiers\":{\"xpgainBoss\":4},\"adjacent\":[58,61]}",
"60": "{\"pos\":[-4,-12],\"type\":12,\"size\":\"Med\",\"name\":\"Boss XP\",\"description\":[\"+10% XP from slain bosses.\"],\"modifiers\":{\"xpgainBoss\":10},\"adjacent\":[56]}",
"61": "{\"pos\":[-2,-15],\"type\":13,\"size\":\"Large\",\"name\":\"Beast Challenger\",\"description\":[\"+25% XP from slain bosses.\",\"-15% XP from slain normal monsters.\"],\"modifiers\":{\"xpgainBoss\":25,\"xpgainNormalMob\":-15},\"adjacent\":[59]}",
"62": "{\"pos\":[0,-11],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[27,63]}",
"63": "{\"pos\":[0,-12],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[62,64]}",
"64": "{\"pos\":[0,-13],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[63,65]}",
"65": "{\"pos\":[0,-14],\"type\":1,\"size\":\"Med\",\"name\":\"XP gain\",\"description\":[\"+7% XP gain\"],\"modifiers\":{\"xpgain\":7},\"adjacent\":[64,334]}",
"66": "{\"pos\":[-2,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[67,315]}",
"67": "{\"pos\":[-3,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[66,68]}",
"68": "{\"pos\":[-4,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[67,71,69]}",
"69": "{\"pos\":[-5,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[68,70]}",
"70": "{\"pos\":[-6,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[69,77]}",
"71": "{\"pos\":[-4,1],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[68,72]}",
"72": "{\"pos\":[-4,2],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[71,73]}",
"73": "{\"pos\":[-3,3],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[72,74]}",
"74": "{\"pos\":[-4,4],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[73,76]}",
"76": "{\"pos\":[-5,3],\"type\":25,\"size\":\"Med\",\"name\":\"Luck\",\"description\":[\"+0.15 luck\"],\"modifiers\":{\"luck\":0.15},\"adjacent\":[74]}",
"77": "{\"pos\":[-7,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[70,78]}",
"78": "{\"pos\":[-8,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[77,79]}",
"79": "{\"pos\":[-9,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[78,80]}",
"80": "{\"pos\":[-10,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[79,82,111,81]}",
"81": "{\"pos\":[-11,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[80,91]}",
"82": "{\"pos\":[-10,-1],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[80,83]}",
"83": "{\"pos\":[-10,-2],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[82,84]}",
"84": "{\"pos\":[-9,-3],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[83,85]}",
"85": "{\"pos\":[-10,-4],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[84,86]}",
"86": "{\"pos\":[-11,-3],\"type\":25,\"size\":\"Med\",\"name\":\"Luck\",\"description\":[\"+0.15 luck\"],\"modifiers\":{\"luck\":0.15},\"adjacent\":[85]}",
"91": "{\"pos\":[-12,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[81,92]}",
"92": "{\"pos\":[-13,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[91,94,161,165]}",
"94": "{\"pos\":[-14,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[92,302]}",
"111": "{\"pos\":[-10,1],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[80,112]}",
"112": "{\"pos\":[-10,2],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[111,113]}",
"113": "{\"pos\":[-10,3],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[112,114]}",
"114": "{\"pos\":[-10,4],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[113,115,127]}",
"115": "{\"pos\":[-11,5],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[114,116]}",
"116": "{\"pos\":[-11,6],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[115,117]}",
"117": "{\"pos\":[-11,7],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[116,118]}",
"118": "{\"pos\":[-11,8],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[117,128,119]}",
"119": "{\"pos\":[-10,9],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[118,120]}",
"120": "{\"pos\":[-9,9],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[119,121]}",
"121": "{\"pos\":[-8,9],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[120,122]}",
"122": "{\"pos\":[-7,9],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[121,129,123]}",
"123": "{\"pos\":[-6,8],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[122,124]}",
"124": "{\"pos\":[-6,7],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[123,125]}",
"125": "{\"pos\":[-7,6],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[124,126]}",
"126": "{\"pos\":[-8,6],\"type\":22,\"size\":\"Small\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+0.25% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":0.25},\"adjacent\":[125,130]}",
"127": "{\"pos\":[-9,5],\"type\":28,\"size\":\"Med\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+1% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":1},\"adjacent\":[114]}",
"128": "{\"pos\":[-12,9],\"type\":28,\"size\":\"Med\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+1% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":1},\"adjacent\":[118]}",
"129": "{\"pos\":[-6,10],\"type\":28,\"size\":\"Med\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+1% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":1},\"adjacent\":[122]}",
"130": "{\"pos\":[-9,7],\"type\":28,\"size\":\"Med\",\"name\":\"Devil/Angel Rooms\",\"description\":[\"+1% chance for the devil/angel room to show up\"],\"modifiers\":{\"devilChance\":1},\"adjacent\":[126,304,303]}",
"143": "{\"pos\":[-15,1],\"type\":39,\"size\":\"Small\",\"name\":\"Bomb Dupe Chance\",\"description\":[\"+0.25% chance for bomb pickups to grant an additional bomb\"],\"modifiers\":{\"bombDupe\":0.25},\"adjacent\":[144,302]}",
"144": "{\"pos\":[-15,2],\"type\":39,\"size\":\"Small\",\"name\":\"Bomb Dupe Chance\",\"description\":[\"+0.25% chance for bomb pickups to grant an additional bomb\"],\"modifiers\":{\"bombDupe\":0.25},\"adjacent\":[143,145]}",
"145": "{\"pos\":[-15,3],\"type\":39,\"size\":\"Small\",\"name\":\"Bomb Dupe Chance\",\"description\":[\"+0.25% chance for bomb pickups to grant an additional bomb\"],\"modifiers\":{\"bombDupe\":0.25},\"adjacent\":[144,146]}",
"146": "{\"pos\":[-15,4],\"type\":39,\"size\":\"Small\",\"name\":\"Bomb Dupe Chance\",\"description\":[\"+0.25% chance for bomb pickups to grant an additional bomb\"],\"modifiers\":{\"bombDupe\":0.25},\"adjacent\":[145,207]}",
"147": "{\"pos\":[-16,0],\"type\":37,\"size\":\"Small\",\"name\":\"Key Dupe Chance\",\"description\":[\"+0.25% chance for key pickups to grant an additional key\"],\"modifiers\":{\"keyDupe\":0.25},\"adjacent\":[148,302]}",
"148": "{\"pos\":[-17,0],\"type\":37,\"size\":\"Small\",\"name\":\"Key Dupe Chance\",\"description\":[\"+0.25% chance for key pickups to grant an additional key\"],\"modifiers\":{\"keyDupe\":0.25},\"adjacent\":[147,149]}",
"149": "{\"pos\":[-18,0],\"type\":37,\"size\":\"Small\",\"name\":\"Key Dupe Chance\",\"description\":[\"+0.25% chance for key pickups to grant an additional key\"],\"modifiers\":{\"keyDupe\":0.25},\"adjacent\":[148,150]}",
"150": "{\"pos\":[-19,0],\"type\":37,\"size\":\"Small\",\"name\":\"Key Dupe Chance\",\"description\":[\"+0.25% chance for key pickups to grant an additional key\"],\"modifiers\":{\"keyDupe\":0.25},\"adjacent\":[149,159]}",
"151": "{\"pos\":[-15,-1],\"type\":35,\"size\":\"Small\",\"name\":\"Coin Dupe Chance\",\"description\":[\"+0.25% chance for coin pickups to grant an additional coin\"],\"modifiers\":{\"coinDupe\":0.25},\"adjacent\":[152,302]}",
"152": "{\"pos\":[-15,-2],\"type\":35,\"size\":\"Small\",\"name\":\"Coin Dupe Chance\",\"description\":[\"+0.25% chance for coin pickups to grant an additional coin\"],\"modifiers\":{\"coinDupe\":0.25},\"adjacent\":[151,153]}",
"153": "{\"pos\":[-15,-3],\"type\":35,\"size\":\"Small\",\"name\":\"Coin Dupe Chance\",\"description\":[\"+0.25% chance for coin pickups to grant an additional coin\"],\"modifiers\":{\"coinDupe\":0.25},\"adjacent\":[152,154]}",
"154": "{\"pos\":[-15,-4],\"type\":35,\"size\":\"Small\",\"name\":\"Coin Dupe Chance\",\"description\":[\"+0.25% chance for coin pickups to grant an additional coin\"],\"modifiers\":{\"coinDupe\":0.25},\"adjacent\":[153,155]}",
"155": "{\"pos\":[-15,-5],\"type\":36,\"size\":\"Med\",\"name\":\"Coin Dupe Chance\",\"description\":[\"+1% chance for coin pickups to grant an additional coin\"],\"modifiers\":{\"coinDupe\":1},\"adjacent\":[154,310]}",
"159": "{\"pos\":[-20,0],\"type\":38,\"size\":\"Med\",\"name\":\"Key Dupe Chance\",\"description\":[\"+1% chance for key pickups to grant an additional key\"],\"modifiers\":{\"keyDupe\":1},\"adjacent\":[150,309]}",
"161": "{\"pos\":[-13,-2],\"type\":33,\"size\":\"Small\",\"name\":\"Mapping Chance\",\"description\":[\"+1% chance for the map to be revealed upon entering a floor\",\"Works from the second floor onwards\"],\"modifiers\":{\"mapChance\":1},\"adjacent\":[92,162]}",
"162": "{\"pos\":[-13,-3],\"type\":33,\"size\":\"Small\",\"name\":\"Mapping Chance\",\"description\":[\"+1% chance for the map to be revealed upon entering a floor\",\"Works from the second floor onwards\"],\"modifiers\":{\"mapChance\":1},\"adjacent\":[161,163]}",
"163": "{\"pos\":[-13,-4],\"type\":33,\"size\":\"Small\",\"name\":\"Mapping Chance\",\"description\":[\"+1% chance for the map to be revealed upon entering a floor\",\"Works from the second floor onwards\"],\"modifiers\":{\"mapChance\":1},\"adjacent\":[162,164]}",
"164": "{\"pos\":[-13,-5],\"type\":33,\"size\":\"Small\",\"name\":\"Mapping Chance\",\"description\":[\"+1% chance for the map to be revealed upon entering a floor\",\"Works from the second floor onwards\"],\"modifiers\":{\"mapChance\":1},\"adjacent\":[163,169]}",
"165": "{\"pos\":[-13,2],\"type\":33,\"size\":\"Small\",\"name\":\"Mapping Chance\",\"description\":[\"+1% chance for the map to be revealed upon entering a floor\",\"Works from the second floor onwards\"],\"modifiers\":{\"mapChance\":1},\"adjacent\":[92,166]}",
"166": "{\"pos\":[-13,3],\"type\":33,\"size\":\"Small\",\"name\":\"Mapping Chance\",\"description\":[\"+1% chance for the map to be revealed upon entering a floor\",\"Works from the second floor onwards\"],\"modifiers\":{\"mapChance\":1},\"adjacent\":[165,167]}",
"167": "{\"pos\":[-13,4],\"type\":33,\"size\":\"Small\",\"name\":\"Mapping Chance\",\"description\":[\"+1% chance for the map to be revealed upon entering a floor\",\"Works from the second floor onwards\"],\"modifiers\":{\"mapChance\":1},\"adjacent\":[166,168]}",
"168": "{\"pos\":[-13,5],\"type\":33,\"size\":\"Small\",\"name\":\"Mapping Chance\",\"description\":[\"+1% chance for the map to be revealed upon entering a floor\",\"Works from the second floor onwards\"],\"modifiers\":{\"mapChance\":1},\"adjacent\":[167,170]}",
"169": "{\"pos\":[-13,-6],\"type\":34,\"size\":\"Med\",\"name\":\"Mapping Chance\",\"description\":[\"+4% chance for the map to be revealed upon entering a floor\",\"Works from the second floor onwards\"],\"modifiers\":{\"mapChance\":4},\"adjacent\":[164]}",
"170": "{\"pos\":[-13,6],\"type\":34,\"size\":\"Med\",\"name\":\"Mapping Chance\",\"description\":[\"+4% chance for the map to be revealed upon entering a floor\",\"Works from the second floor onwards\"],\"modifiers\":{\"mapChance\":4},\"adjacent\":[168]}",
"171": "{\"pos\":[0,2],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[172,315]}",
"172": "{\"pos\":[0,3],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[171,173]}",
"173": "{\"pos\":[0,4],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[172,174]}",
"174": "{\"pos\":[0,5],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[173,175]}",
"175": "{\"pos\":[0,6],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[174,176]}",
"176": "{\"pos\":[0,7],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[175,177]}",
"177": "{\"pos\":[0,8],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[176,178]}",
"178": "{\"pos\":[1,9],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[177,179]}",
"179": "{\"pos\":[2,10],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[178,180]}",
"180": "{\"pos\":[3,11],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[179,195]}",
"195": "{\"pos\":[2,12],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[196,180]}",
"196": "{\"pos\":[1,13],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[195,197]}",
"197": "{\"pos\":[0,14],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[196,198]}",
"198": "{\"pos\":[-1,13],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[197,199]}",
"199": "{\"pos\":[-2,12],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[198,324]}",
"207": "{\"pos\":[-15,5],\"type\":40,\"size\":\"Med\",\"name\":\"Bomb Dupe Chance\",\"description\":[\"+1% chance for bomb pickups to grant an additional bomb\"],\"modifiers\":{\"bombDupe\":1},\"adjacent\":[146,308]}",
"214": "{\"pos\":[4,0],\"type\":24,\"size\":\"Small\",\"name\":\"Damage\",\"description\":[\"+0.02 damage\"],\"modifiers\":{\"damage\":0.02},\"adjacent\":[215,317]}",
"215": "{\"pos\":[5,0],\"type\":24,\"size\":\"Small\",\"name\":\"Damage\",\"description\":[\"+0.02 damage\"],\"modifiers\":{\"damage\":0.02},\"adjacent\":[214,216]}",
"216": "{\"pos\":[6,0],\"type\":31,\"size\":\"Small\",\"name\":\"Tears\",\"description\":[\"+0.03 tears\"],\"modifiers\":{\"tears\":0.03},\"adjacent\":[215,217]}",
"217": "{\"pos\":[7,0],\"type\":31,\"size\":\"Small\",\"name\":\"Tears\",\"description\":[\"+0.03 tears\"],\"modifiers\":{\"tears\":0.03},\"adjacent\":[216,218]}",
"218": "{\"pos\":[8,0],\"type\":21,\"size\":\"Small\",\"name\":\"Shot Speed\",\"description\":[\"+0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":0.02},\"adjacent\":[217,219]}",
"219": "{\"pos\":[9,0],\"type\":21,\"size\":\"Small\",\"name\":\"Shot Speed\",\"description\":[\"+0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":0.02},\"adjacent\":[218,220]}",
"220": "{\"pos\":[10,0],\"type\":20,\"size\":\"Small\",\"name\":\"Range\",\"description\":[\"+0.05 range\"],\"modifiers\":{\"range\":0.05},\"adjacent\":[219,221]}",
"221": "{\"pos\":[11,0],\"type\":20,\"size\":\"Small\",\"name\":\"Range\",\"description\":[\"+0.05 range\"],\"modifiers\":{\"range\":0.05},\"adjacent\":[220,222]}",
"222": "{\"pos\":[12,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[221,239,223]}",
"223": "{\"pos\":[13,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[222,245,224]}",
"224": "{\"pos\":[14,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[223,251,225]}",
"225": "{\"pos\":[15,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[224,269,318]}",
"239": "{\"pos\":[13,-1],\"type\":24,\"size\":\"Small\",\"name\":\"Damage\",\"description\":[\"+0.02 damage\"],\"modifiers\":{\"damage\":0.02},\"adjacent\":[222,240]}",
"240": "{\"pos\":[13,-2],\"type\":24,\"size\":\"Small\",\"name\":\"Damage\",\"description\":[\"+0.02 damage\"],\"modifiers\":{\"damage\":0.02},\"adjacent\":[239,241]}",
"241": "{\"pos\":[13,-3],\"type\":24,\"size\":\"Small\",\"name\":\"Damage\",\"description\":[\"+0.02 damage\"],\"modifiers\":{\"damage\":0.02},\"adjacent\":[240,242]}",
"242": "{\"pos\":[13,-4],\"type\":24,\"size\":\"Small\",\"name\":\"Damage\",\"description\":[\"+0.02 damage\"],\"modifiers\":{\"damage\":0.02},\"adjacent\":[241,243]}",
"243": "{\"pos\":[13,-5],\"type\":24,\"size\":\"Small\",\"name\":\"Damage\",\"description\":[\"+0.02 damage\"],\"modifiers\":{\"damage\":0.02},\"adjacent\":[242,244]}",
"244": "{\"pos\":[13,-6],\"type\":30,\"size\":\"Med\",\"name\":\"Damage\",\"description\":[\"+0.1 damage\"],\"modifiers\":{\"damage\":0.1},\"adjacent\":[243,409]}",
"245": "{\"pos\":[14,1],\"type\":31,\"size\":\"Small\",\"name\":\"Tears\",\"description\":[\"+0.03 tears\"],\"modifiers\":{\"tears\":0.03},\"adjacent\":[223,246]}",
"246": "{\"pos\":[14,2],\"type\":31,\"size\":\"Small\",\"name\":\"Tears\",\"description\":[\"+0.03 tears\"],\"modifiers\":{\"tears\":0.03},\"adjacent\":[245,247]}",
"247": "{\"pos\":[14,3],\"type\":31,\"size\":\"Small\",\"name\":\"Tears\",\"description\":[\"+0.03 tears\"],\"modifiers\":{\"tears\":0.03},\"adjacent\":[246,248]}",
"248": "{\"pos\":[14,4],\"type\":31,\"size\":\"Small\",\"name\":\"Tears\",\"description\":[\"+0.03 tears\"],\"modifiers\":{\"tears\":0.03},\"adjacent\":[247,249]}",
"249": "{\"pos\":[14,5],\"type\":31,\"size\":\"Small\",\"name\":\"Tears\",\"description\":[\"+0.03 tears\"],\"modifiers\":{\"tears\":0.03},\"adjacent\":[248,250]}",
"250": "{\"pos\":[14,6],\"type\":32,\"size\":\"Med\",\"name\":\"Tears\",\"description\":[\"+0.1 tears\"],\"modifiers\":{\"tears\":0.1},\"adjacent\":[249,415]}",
"251": "{\"pos\":[15,-1],\"type\":21,\"size\":\"Small\",\"name\":\"Shot Speed\",\"description\":[\"+0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":0.02},\"adjacent\":[224,252]}",
"252": "{\"pos\":[15,-2],\"type\":21,\"size\":\"Small\",\"name\":\"Shot Speed\",\"description\":[\"+0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":0.02},\"adjacent\":[251,253]}",
"253": "{\"pos\":[15,-3],\"type\":21,\"size\":\"Small\",\"name\":\"Shot Speed\",\"description\":[\"+0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":0.02},\"adjacent\":[252,254]}",
"254": "{\"pos\":[15,-4],\"type\":21,\"size\":\"Small\",\"name\":\"Shot Speed\",\"description\":[\"+0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":0.02},\"adjacent\":[253,255]}",
"255": "{\"pos\":[15,-5],\"type\":21,\"size\":\"Small\",\"name\":\"Shot Speed\",\"description\":[\"+0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":0.02},\"adjacent\":[254,256]}",
"256": "{\"pos\":[15,-6],\"type\":27,\"size\":\"Med\",\"name\":\"Shot Speed\",\"description\":[\"+0.1 shot speed\"],\"modifiers\":{\"shotSpeed\":0.1},\"adjacent\":[255,411]}",
"263": "{\"pos\":[17,-1],\"type\":20,\"size\":\"Small\",\"name\":\"Range\",\"description\":[\"+0.05 range\"],\"modifiers\":{\"range\":0.05},\"adjacent\":[269,264]}",
"264": "{\"pos\":[17,-2],\"type\":20,\"size\":\"Small\",\"name\":\"Range\",\"description\":[\"+0.05 range\"],\"modifiers\":{\"range\":0.05},\"adjacent\":[263,265]}",
"265": "{\"pos\":[17,-3],\"type\":20,\"size\":\"Small\",\"name\":\"Range\",\"description\":[\"+0.05 range\"],\"modifiers\":{\"range\":0.05},\"adjacent\":[264,266]}",
"266": "{\"pos\":[17,-4],\"type\":20,\"size\":\"Small\",\"name\":\"Range\",\"description\":[\"+0.05 range\"],\"modifiers\":{\"range\":0.05},\"adjacent\":[265,267]}",
"267": "{\"pos\":[17,-5],\"type\":20,\"size\":\"Small\",\"name\":\"Range\",\"description\":[\"+0.05 range\"],\"modifiers\":{\"range\":0.05},\"adjacent\":[266,268]}",
"268": "{\"pos\":[17,-6],\"type\":26,\"size\":\"Med\",\"name\":\"Range\",\"description\":[\"+0.2 range\"],\"modifiers\":{\"range\":0.2},\"adjacent\":[267,413]}",
"269": "{\"pos\":[16,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[225,263,270]}",
"270": "{\"pos\":[17,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[269,271,279]}",
"271": "{\"pos\":[18,1],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[270,272]}",
"272": "{\"pos\":[18,2],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[271,273]}",
"273": "{\"pos\":[18,3],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[272,274]}",
"274": "{\"pos\":[18,4],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[273,275]}",
"275": "{\"pos\":[18,5],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[274,276]}",
"276": "{\"pos\":[18,6],\"type\":25,\"size\":\"Med\",\"name\":\"Luck\",\"description\":[\"+0.15 luck\"],\"modifiers\":{\"luck\":0.15},\"adjacent\":[275,419]}",
"278": "{\"pos\":[19,0],\"type\":25,\"size\":\"Med\",\"name\":\"Luck\",\"description\":[\"+0.15 luck\"],\"modifiers\":{\"luck\":0.15},\"adjacent\":[279,431]}",
"279": "{\"pos\":[18,0],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[270,278,444]}",
"282": "{\"pos\":[-8,-7],\"type\":5,\"size\":\"Med\",\"name\":\"Boss Challenge XP\",\"description\":[\"Apply challenge room XP bonuses to boss challenge rooms.\"],\"modifiers\":{\"bossChallengeXP\":true},\"adjacent\":[41]}",
"283": "{\"pos\":[1,-3],\"type\":7,\"size\":\"Small\",\"name\":\"Respec Chance\",\"description\":[\"+10% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":10},\"adjacent\":[3,284]}",
"284": "{\"pos\":[2,-3],\"type\":7,\"size\":\"Small\",\"name\":\"Respec Chance\",\"description\":[\"+10% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":10},\"adjacent\":[283,285]}",
"285": "{\"pos\":[3,-3],\"type\":7,\"size\":\"Small\",\"name\":\"Respec Chance\",\"description\":[\"+10% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":10},\"adjacent\":[284,286]}",
"286": "{\"pos\":[4,-3],\"type\":7,\"size\":\"Small\",\"name\":\"Respec Chance\",\"description\":[\"+10% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":10},\"adjacent\":[285,287]}",
"287": "{\"pos\":[5,-3],\"type\":8,\"size\":\"Med\",\"name\":\"Respec Chance\",\"description\":[\"+30% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":30},\"adjacent\":[286,288,292,301]}",
"288": "{\"pos\":[6,-3],\"type\":7,\"size\":\"Small\",\"name\":\"Respec Chance\",\"description\":[\"+10% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":10},\"adjacent\":[287,289]}",
"289": "{\"pos\":[7,-3],\"type\":7,\"size\":\"Small\",\"name\":\"Respec Chance\",\"description\":[\"+10% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":10},\"adjacent\":[288,290]}",
"290": "{\"pos\":[8,-3],\"type\":7,\"size\":\"Small\",\"name\":\"Respec Chance\",\"description\":[\"+10% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":10},\"adjacent\":[289,291]}",
"291": "{\"pos\":[9,-3],\"type\":7,\"size\":\"Small\",\"name\":\"Respec Chance\",\"description\":[\"+10% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":10},\"adjacent\":[290,296]}",
"292": "{\"pos\":[6,-4],\"type\":7,\"size\":\"Small\",\"name\":\"Respec Chance\",\"description\":[\"+10% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":10},\"adjacent\":[287,293]}",
"293": "{\"pos\":[7,-5],\"type\":7,\"size\":\"Small\",\"name\":\"Respec Chance\",\"description\":[\"+10% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":10},\"adjacent\":[292,294]}",
"294": "{\"pos\":[8,-6],\"type\":7,\"size\":\"Small\",\"name\":\"Respec Chance\",\"description\":[\"+10% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":10},\"adjacent\":[293,295]}",
"295": "{\"pos\":[9,-7],\"type\":7,\"size\":\"Small\",\"name\":\"Respec Chance\",\"description\":[\"+10% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":10},\"adjacent\":[294,297]}",
"296": "{\"pos\":[10,-3],\"type\":8,\"size\":\"Med\",\"name\":\"Respec Chance\",\"description\":[\"+30% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":30},\"adjacent\":[291]}",
"297": "{\"pos\":[10,-8],\"type\":8,\"size\":\"Med\",\"name\":\"Respec Chance\",\"description\":[\"+30% chance to gain a respec point\",\"when completing a floor.\"],\"modifiers\":{\"respecChance\":30},\"adjacent\":[295]}",
"300": "{\"pos\":[1,-8],\"type\":3,\"size\":\"Large\",\"name\":\"Unholy Growth\",\"description\":[\"+20% XP gain\",\"Starting stats are 5% lower for all characters.\"],\"modifiers\":{\"xpgain\":20,\"allstatsPerc\":-5},\"adjacent\":[25]}",
"301": "{\"pos\":[5,-2],\"type\":9,\"size\":\"Large\",\"name\":\"Relearning\",\"description\":[\"Can no longer gain respec points from completing floors.\",\"Gain 10 respec points when winning a run, and\",\"additionally gain 2 respec points per completed floor in that run.\"],\"modifiers\":{\"relearning\":true},\"adjacent\":[287]}",
"302": "{\"pos\":[-15,0],\"type\":41,\"size\":\"Med\",\"name\":\"Good Deeds\",\"description\":[\"Helping any type of beggar grants +0.02 luck\"],\"modifiers\":{\"beggarLuck\":0.02},\"adjacent\":[94,151,147,143,353]}",
"303": "{\"pos\":[-8,8],\"type\":46,\"size\":\"Large\",\"name\":\"Heaven's Favour\",\"description\":[\"+1 to a random stat when entering an angel room.\",\"-1 to a random stat when entering a devil room.\",\"Entering a devil room will trigger a curse on the next floor.\"],\"modifiers\":{\"heavenFavour\":true},\"adjacent\":[130]}",
"304": "{\"pos\":[-10,8],\"type\":45,\"size\":\"Large\",\"name\":\"Hell's Favour\",\"description\":[\"+1 to a random stat when entering a devil room.\",\"-1 to a random stat when entering an angel room.\",\"Entering an angel room will trigger a curse on the next floor.\"],\"modifiers\":{\"hellFavour\":true},\"adjacent\":[130]}",
"308": "{\"pos\":[-15,6],\"type\":42,\"size\":\"Med\",\"name\":\"Grab Bags\",\"description\":[\"+0.25% chance to spawn a grab-bag when collecting a pickup\"],\"modifiers\":{\"grabBag\":0.25},\"adjacent\":[207]}",
"309": "{\"pos\":[-21,0],\"type\":42,\"size\":\"Med\",\"name\":\"Grab Bags\",\"description\":[\"+0.25% chance to spawn a grab-bag when collecting a pickup\"],\"modifiers\":{\"grabBag\":0.25},\"adjacent\":[159]}",
"310": "{\"pos\":[-15,-6],\"type\":42,\"size\":\"Med\",\"name\":\"Grab Bags\",\"description\":[\"+0.25% chance to spawn a grab-bag when collecting a pickup\"],\"modifiers\":{\"grabBag\":0.25},\"adjacent\":[155]}",
"315": "{\"pos\":[0,0],\"type\":6,\"size\":\"Large\",\"name\":\"Leveling Of Isaac\",\"description\":[\"+0.02 all stats\"],\"modifiers\":{\"allstats\":0.02},\"adjacent\":[2,66,171,316,383],\"alwaysAvailable\":true}",
"316": "{\"pos\":[2,0],\"type\":23,\"size\":\"Small\",\"name\":\"Speed\",\"description\":[\"+0.01 speed\"],\"modifiers\":{\"speed\":0.01},\"adjacent\":[315,317]}",
"317": "{\"pos\":[3,0],\"type\":23,\"size\":\"Small\",\"name\":\"Speed\",\"description\":[\"+0.01 speed\"],\"modifiers\":{\"speed\":0.01},\"adjacent\":[316,214]}",
"318": "{\"pos\":[16,1],\"type\":23,\"size\":\"Small\",\"name\":\"Speed\",\"description\":[\"+0.01 speed\"],\"modifiers\":{\"speed\":0.01},\"adjacent\":[225,319]}",
"319": "{\"pos\":[16,2],\"type\":23,\"size\":\"Small\",\"name\":\"Speed\",\"description\":[\"+0.01 speed\"],\"modifiers\":{\"speed\":0.01},\"adjacent\":[318,320]}",
"320": "{\"pos\":[16,3],\"type\":23,\"size\":\"Small\",\"name\":\"Speed\",\"description\":[\"+0.01 speed\"],\"modifiers\":{\"speed\":0.01},\"adjacent\":[319,321]}",
"321": "{\"pos\":[16,4],\"type\":23,\"size\":\"Small\",\"name\":\"Speed\",\"description\":[\"+0.01 speed\"],\"modifiers\":{\"speed\":0.01},\"adjacent\":[320,322]}",
"322": "{\"pos\":[16,5],\"type\":23,\"size\":\"Small\",\"name\":\"Speed\",\"description\":[\"+0.01 speed\"],\"modifiers\":{\"speed\":0.01},\"adjacent\":[321,323]}",
"323": "{\"pos\":[16,6],\"type\":29,\"size\":\"Med\",\"name\":\"Speed\",\"description\":[\"+0.04 speed\"],\"modifiers\":{\"speed\":0.04},\"adjacent\":[322,417]}",
"324": "{\"pos\":[-3,11],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[199,325]}",
"325": "{\"pos\":[-2,10],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[324,326]}",
"326": "{\"pos\":[-1,9],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[325,327]}",
"327": "{\"pos\":[0,10],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[326,328]}",
"328": "{\"pos\":[1,11],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[327,329]}",
"329": "{\"pos\":[0,12],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[328,330]}",
"330": "{\"pos\":[-1,11],\"type\":44,\"size\":\"Small\",\"name\":\"Luck Down\",\"description\":[\"-0.03 luck\"],\"modifiers\":{\"luck\":-0.03},\"adjacent\":[329,333]}",
"333": "{\"pos\":[0,11],\"type\":43,\"size\":\"Large\",\"name\":\"Cosmic Realignment\",\"description\":[\"Allocate to choose a character. Once chosen, you may receive unlocks as if playing\",\"as that character while using a different one.\",\"Beware the cosmic curse each character brings...\"],\"modifiers\":{\"cosmicRealignment\":true},\"adjacent\":[330]}",
"334": "{\"pos\":[0,-15],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[65,335]}",
"335": "{\"pos\":[0,-16],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[334,336]}",
"336": "{\"pos\":[0,-17],\"type\":0,\"size\":\"Small\",\"name\":\"XP gain\",\"description\":[\"+2% XP gain\"],\"modifiers\":{\"xpgain\":2},\"adjacent\":[335,337,341,345]}",
"337": "{\"pos\":[-1,-17],\"type\":304,\"size\":\"Small\",\"name\":\"Poop XP\",\"description\":[\"Gain +3 xp when destroying poop.\"],\"modifiers\":{\"poopXP\":3},\"adjacent\":[336,338]}",
"338": "{\"pos\":[-2,-17],\"type\":304,\"size\":\"Small\",\"name\":\"Poop XP\",\"description\":[\"Gain +3 xp when destroying poop.\"],\"modifiers\":{\"poopXP\":3},\"adjacent\":[337,339]}",
"339": "{\"pos\":[-3,-17],\"type\":304,\"size\":\"Small\",\"name\":\"Poop XP\",\"description\":[\"Gain +3 xp when destroying poop.\"],\"modifiers\":{\"poopXP\":3},\"adjacent\":[338,340]}",
"340": "{\"pos\":[-4,-17],\"type\":304,\"size\":\"Small\",\"name\":\"Poop XP\",\"description\":[\"Gain +3 xp when destroying poop.\"],\"modifiers\":{\"poopXP\":3},\"adjacent\":[339]}",
"341": "{\"pos\":[0,-18],\"type\":303,\"size\":\"Small\",\"name\":\"Fire XP\",\"description\":[\"Gain +3 xp when putting out fires.\"],\"modifiers\":{\"fireXP\":3},\"adjacent\":[336,342]}",
"342": "{\"pos\":[0,-19],\"type\":303,\"size\":\"Small\",\"name\":\"Fire XP\",\"description\":[\"Gain +3 xp when putting out fires.\"],\"modifiers\":{\"fireXP\":3},\"adjacent\":[341,343]}",
"343": "{\"pos\":[0,-20],\"type\":303,\"size\":\"Small\",\"name\":\"Fire XP\",\"description\":[\"Gain +3 xp when putting out fires.\"],\"modifiers\":{\"fireXP\":3},\"adjacent\":[342,344]}",
"344": "{\"pos\":[0,-21],\"type\":303,\"size\":\"Small\",\"name\":\"Fire XP\",\"description\":[\"Gain +3 xp when putting out fires.\"],\"modifiers\":{\"fireXP\":3},\"adjacent\":[343]}",
"345": "{\"pos\":[1,-17],\"type\":309,\"size\":\"Small\",\"name\":\"Tinted Rock XP\",\"description\":[\"Gain +8 xp when destroying tinted rocks.\"],\"modifiers\":{\"tintedRockXP\":8},\"adjacent\":[336,346]}",
"346": "{\"pos\":[2,-17],\"type\":309,\"size\":\"Small\",\"name\":\"Tinted Rock XP\",\"description\":[\"Gain +8 xp when destroying tinted rocks.\"],\"modifiers\":{\"tintedRockXP\":8},\"adjacent\":[345,347]}",
"347": "{\"pos\":[3,-17],\"type\":309,\"size\":\"Small\",\"name\":\"Tinted Rock XP\",\"description\":[\"Gain +8 xp when destroying tinted rocks.\"],\"modifiers\":{\"tintedRockXP\":8},\"adjacent\":[346,348]}",
"348": "{\"pos\":[4,-17],\"type\":309,\"size\":\"Small\",\"name\":\"Tinted Rock XP\",\"description\":[\"Gain +8 xp when destroying tinted rocks.\"],\"modifiers\":{\"tintedRockXP\":8},\"adjacent\":[347]}",
"349": "{\"pos\":[5,-7],\"type\":304,\"size\":\"Small\",\"name\":\"Poop XP\",\"description\":[\"Gain +3 xp when destroying poop.\"],\"modifiers\":{\"poopXP\":3},\"adjacent\":[17]}",
"350": "{\"pos\":[5,-8],\"type\":303,\"size\":\"Small\",\"name\":\"Fire XP\",\"description\":[\"Gain +3 xp when putting out fires.\"],\"modifiers\":{\"fireXP\":3},\"adjacent\":[17]}",
"352": "{\"pos\":[4,-8],\"type\":309,\"size\":\"Small\",\"name\":\"Tinted Rock XP\",\"description\":[\"Gain +8 xp when destroying tinted rocks.\"],\"modifiers\":{\"tintedRockXP\":8},\"adjacent\":[17]}",
"353": "{\"pos\":[-16,-1],\"type\":299,\"size\":\"Small\",\"name\":\"Lucky Pennies\",\"description\":[\"0.15% chance to replace penny drops with a lucky penny.\"],\"modifiers\":{\"luckyPennyChance\":0.15},\"adjacent\":[302,354]}",
"354": "{\"pos\":[-17,-2],\"type\":299,\"size\":\"Small\",\"name\":\"Lucky Pennies\",\"description\":[\"0.15% chance to replace penny drops with a lucky penny.\"],\"modifiers\":{\"luckyPennyChance\":0.15},\"adjacent\":[353,365,355]}",
"355": "{\"pos\":[-18,-3],\"type\":299,\"size\":\"Small\",\"name\":\"Lucky Pennies\",\"description\":[\"0.15% chance to replace penny drops with a lucky penny.\"],\"modifiers\":{\"luckyPennyChance\":0.15},\"adjacent\":[354,356]}",
"356": "{\"pos\":[-19,-4],\"type\":299,\"size\":\"Small\",\"name\":\"Lucky Pennies\",\"description\":[\"0.15% chance to replace penny drops with a lucky penny.\"],\"modifiers\":{\"luckyPennyChance\":0.15},\"adjacent\":[355,374,357]}",
"357": "{\"pos\":[-20,-5],\"type\":299,\"size\":\"Small\",\"name\":\"Lucky Pennies\",\"description\":[\"0.15% chance to replace penny drops with a lucky penny.\"],\"modifiers\":{\"luckyPennyChance\":0.15},\"adjacent\":[356,358]}",
"358": "{\"pos\":[-21,-6],\"type\":299,\"size\":\"Small\",\"name\":\"Lucky Pennies\",\"description\":[\"0.15% chance to replace penny drops with a lucky penny.\"],\"modifiers\":{\"luckyPennyChance\":0.15},\"adjacent\":[357,378]}",
"365": "{\"pos\":[-18,-2],\"type\":300,\"size\":\"Small\",\"name\":\"Card Floor Luck\",\"description\":[\"1% increased luck for the current floor when you use a card.\"],\"modifiers\":{\"cardFloorLuck\":1},\"adjacent\":[354,366]}",
"366": "{\"pos\":[-19,-2],\"type\":300,\"size\":\"Small\",\"name\":\"Card Floor Luck\",\"description\":[\"1% increased luck for the current floor when you use a card.\"],\"modifiers\":{\"cardFloorLuck\":1},\"adjacent\":[365,367]}",
"367": "{\"pos\":[-20,-2],\"type\":300,\"size\":\"Small\",\"name\":\"Card Floor Luck\",\"description\":[\"1% increased luck for the current floor when you use a card.\"],\"modifiers\":{\"cardFloorLuck\":1},\"adjacent\":[366,368]}",
"368": "{\"pos\":[-21,-2],\"type\":300,\"size\":\"Small\",\"name\":\"Card Floor Luck\",\"description\":[\"1% increased luck for the current floor when you use a card.\"],\"modifiers\":{\"cardFloorLuck\":1},\"adjacent\":[367]}",
"374": "{\"pos\":[-20,-4],\"type\":301,\"size\":\"Small\",\"name\":\"Pill Floor Luck\",\"description\":[\"1% increased luck for the current floor when you consume a pill\"],\"modifiers\":{\"pillFloorLuck\":1},\"adjacent\":[356,375]}",
"375": "{\"pos\":[-21,-4],\"type\":301,\"size\":\"Small\",\"name\":\"Pill Floor Luck\",\"description\":[\"1% increased luck for the current floor when you consume a pill\"],\"modifiers\":{\"pillFloorLuck\":1},\"adjacent\":[374,376]}",
"376": "{\"pos\":[-22,-4],\"type\":301,\"size\":\"Small\",\"name\":\"Pill Floor Luck\",\"description\":[\"1% increased luck for the current floor when you consume a pill\"],\"modifiers\":{\"pillFloorLuck\":1},\"adjacent\":[375,377]}",
"377": "{\"pos\":[-23,-4],\"type\":301,\"size\":\"Small\",\"name\":\"Pill Floor Luck\",\"description\":[\"1% increased luck for the current floor when you consume a pill\"],\"modifiers\":{\"pillFloorLuck\":1},\"adjacent\":[376]}",
"378": "{\"pos\":[-22,-7],\"type\":302,\"size\":\"Small\",\"name\":\"Secret Room Floor Luck\",\"description\":[\"+0.1 luck for the current floor when first entering a secret or super secret room.\"],\"modifiers\":{\"secretRoomFloorLuck\":0.1},\"adjacent\":[358,379,382,381,380,434]}",
"379": "{\"pos\":[-22,-6],\"type\":302,\"size\":\"Small\",\"name\":\"Secret Room Floor Luck\",\"description\":[\"+0.1 luck for the current floor when first entering a secret or super secret room.\"],\"modifiers\":{\"secretRoomFloorLuck\":0.1},\"adjacent\":[378]}",
"380": "{\"pos\":[-21,-7],\"type\":302,\"size\":\"Small\",\"name\":\"Secret Room Floor Luck\",\"description\":[\"+0.1 luck for the current floor when first entering a secret or super secret room.\"],\"modifiers\":{\"secretRoomFloorLuck\":0.1},\"adjacent\":[378]}",
"381": "{\"pos\":[-22,-8],\"type\":302,\"size\":\"Small\",\"name\":\"Secret Room Floor Luck\",\"description\":[\"+0.1 luck for the current floor when first entering a secret or super secret room.\"],\"modifiers\":{\"secretRoomFloorLuck\":0.1},\"adjacent\":[378]}",
"382": "{\"pos\":[-23,-7],\"type\":302,\"size\":\"Small\",\"name\":\"Secret Room Floor Luck\",\"description\":[\"+0.1 luck for the current floor when first entering a secret or super secret room.\"],\"modifiers\":{\"secretRoomFloorLuck\":0.1},\"adjacent\":[378]}",
"383": "{\"pos\":[2,2],\"type\":305,\"size\":\"Small\",\"name\":\"Planetarium Chance\",\"description\":[\"0.15% increased chance of finding a planetarium.\"],\"modifiers\":{\"planetariumChance\":0.15},\"adjacent\":[315,384]}",
"384": "{\"pos\":[3,3],\"type\":305,\"size\":\"Small\",\"name\":\"Planetarium Chance\",\"description\":[\"0.15% increased chance of finding a planetarium.\"],\"modifiers\":{\"planetariumChance\":0.15},\"adjacent\":[383,385]}",
"385": "{\"pos\":[4,4],\"type\":305,\"size\":\"Small\",\"name\":\"Planetarium Chance\",\"description\":[\"0.15% increased chance of finding a planetarium.\"],\"modifiers\":{\"planetariumChance\":0.15},\"adjacent\":[384,386]}",
"386": "{\"pos\":[5,5],\"type\":305,\"size\":\"Small\",\"name\":\"Planetarium Chance\",\"description\":[\"0.15% increased chance of finding a planetarium.\"],\"modifiers\":{\"planetariumChance\":0.15},\"adjacent\":[385,391]}",
"387": "{\"pos\":[5,6],\"type\":305,\"size\":\"Small\",\"name\":\"Planetarium Chance\",\"description\":[\"0.15% increased chance of finding a planetarium.\"],\"modifiers\":{\"planetariumChance\":0.15},\"adjacent\":[391]}",
"388": "{\"pos\":[6,5],\"type\":305,\"size\":\"Small\",\"name\":\"Planetarium Chance\",\"description\":[\"0.15% increased chance of finding a planetarium.\"],\"modifiers\":{\"planetariumChance\":0.15},\"adjacent\":[391]}",
"389": "{\"pos\":[7,6],\"type\":305,\"size\":\"Small\",\"name\":\"Planetarium Chance\",\"description\":[\"0.15% increased chance of finding a planetarium.\"],\"modifiers\":{\"planetariumChance\":0.15},\"adjacent\":[391]}",
"390": "{\"pos\":[6,7],\"type\":305,\"size\":\"Small\",\"name\":\"Planetarium Chance\",\"description\":[\"0.15% increased chance of finding a planetarium.\"],\"modifiers\":{\"planetariumChance\":0.15},\"adjacent\":[391]}",
"391": "{\"pos\":[6,6],\"type\":306,\"size\":\"Med\",\"name\":\"Planetarium Chance\",\"description\":[\"1% increased chance of finding a planetarium.\"],\"modifiers\":{\"planetariumChance\":1},\"adjacent\":[386,392,387,388,389,390,406,405]}",
"392": "{\"pos\":[7,7],\"type\":305,\"size\":\"Small\",\"name\":\"Planetarium Chance\",\"description\":[\"0.15% increased chance of finding a planetarium.\"],\"modifiers\":{\"planetariumChance\":0.15},\"adjacent\":[391,393]}",
"393": "{\"pos\":[8,8],\"type\":305,\"size\":\"Small\",\"name\":\"Planetarium Chance\",\"description\":[\"0.15% increased chance of finding a planetarium.\"],\"modifiers\":{\"planetariumChance\":0.15},\"adjacent\":[392,394]}",
"394": "{\"pos\":[9,9],\"type\":305,\"size\":\"Small\",\"name\":\"Planetarium Chance\",\"description\":[\"0.15% increased chance of finding a planetarium.\"],\"modifiers\":{\"planetariumChance\":0.15},\"adjacent\":[393,395]}",
"395": "{\"pos\":[10,10],\"type\":305,\"size\":\"Small\",\"name\":\"Planetarium Chance\",\"description\":[\"0.15% increased chance of finding a planetarium.\"],\"modifiers\":{\"planetariumChance\":0.15},\"adjacent\":[394,396]}",
"396": "{\"pos\":[11,11],\"type\":307,\"size\":\"Med\",\"name\":\"Planetarium Blessing\",\"description\":[\"+3% all stats when entering a planetarium for the first time in the run.\"],\"modifiers\":{\"planetariumAllstats\":3},\"adjacent\":[395,403,402,401,404]}",
"401": "{\"pos\":[11,10],\"type\":308,\"size\":\"Small\",\"name\":\"Secret Room Random Stat\",\"description\":[\"+0.01 to a random stat when first entering a secret room.\",\"Each node with this effect will roll a random stat independently.\"],\"modifiers\":{\"secretRoomRandomStat\":1},\"adjacent\":[396]}",
"402": "{\"pos\":[10,11],\"type\":308,\"size\":\"Small\",\"name\":\"Secret Room Random Stat\",\"description\":[\"+0.01 to a random stat when first entering a secret room.\",\"Each node with this effect will roll a random stat independently.\"],\"modifiers\":{\"secretRoomRandomStat\":1},\"adjacent\":[396]}",
"403": "{\"pos\":[11,12],\"type\":308,\"size\":\"Small\",\"name\":\"Secret Room Random Stat\",\"description\":[\"+0.01 to a random stat when first entering a secret room.\",\"Each node with this effect will roll a random stat independently.\"],\"modifiers\":{\"secretRoomRandomStat\":1},\"adjacent\":[396]}",
"404": "{\"pos\":[12,11],\"type\":308,\"size\":\"Small\",\"name\":\"Secret Room Random Stat\",\"description\":[\"+0.01 to a random stat when first entering a secret room.\",\"Each node with this effect will roll a random stat independently.\"],\"modifiers\":{\"secretRoomRandomStat\":1},\"adjacent\":[396]}",
"405": "{\"pos\":[8,4],\"type\":308,\"size\":\"Small\",\"name\":\"Secret Room Random Stat\",\"description\":[\"+0.01 to a random stat when first entering a secret room.\",\"Each node with this effect will roll a random stat independently.\"],\"modifiers\":{\"secretRoomRandomStat\":1},\"adjacent\":[391,429]}",
"406": "{\"pos\":[4,8],\"type\":308,\"size\":\"Small\",\"name\":\"Secret Room Random Stat\",\"description\":[\"+0.01 to a random stat when first entering a secret room.\",\"Each node with this effect will roll a random stat independently.\"],\"modifiers\":{\"secretRoomRandomStat\":1},\"adjacent\":[391,428]}",
"409": "{\"pos\":[13,-7],\"type\":24,\"size\":\"Small\",\"name\":\"Damage\",\"description\":[\"+0.01 damage\"],\"modifiers\":{\"damage\":0.01},\"adjacent\":[244,410]}",
"410": "{\"pos\":[13,-8],\"type\":24,\"size\":\"Small\",\"name\":\"Damage\",\"description\":[\"+0.01 damage\"],\"modifiers\":{\"damage\":0.01},\"adjacent\":[409,426]}",
"411": "{\"pos\":[15,-7],\"type\":21,\"size\":\"Small\",\"name\":\"Shot Speed\",\"description\":[\"+0.01 shot speed\"],\"modifiers\":{\"shotSpeed\":0.01},\"adjacent\":[256,412]}",
"412": "{\"pos\":[15,-8],\"type\":21,\"size\":\"Small\",\"name\":\"Shot Speed\",\"description\":[\"+0.01 shot speed\"],\"modifiers\":{\"shotSpeed\":0.01},\"adjacent\":[411,443]}",
"413": "{\"pos\":[17,-7],\"type\":20,\"size\":\"Small\",\"name\":\"Range\",\"description\":[\"+0.02 range\"],\"modifiers\":{\"range\":0.02},\"adjacent\":[268,414]}",
"414": "{\"pos\":[17,-8],\"type\":20,\"size\":\"Small\",\"name\":\"Range\",\"description\":[\"+0.02 range\"],\"modifiers\":{\"range\":0.02},\"adjacent\":[413,424]}",
"415": "{\"pos\":[14,7],\"type\":31,\"size\":\"Small\",\"name\":\"Tears\",\"description\":[\"+0.01 tears\"],\"modifiers\":{\"tears\":0.01},\"adjacent\":[250,416]}",
"416": "{\"pos\":[14,8],\"type\":31,\"size\":\"Small\",\"name\":\"Tears\",\"description\":[\"+0.01 tears\"],\"modifiers\":{\"tears\":0.01},\"adjacent\":[415,425]}",
"417": "{\"pos\":[16,7],\"type\":23,\"size\":\"Small\",\"name\":\"Speed\",\"description\":[\"+0.01 speed\"],\"modifiers\":{\"speed\":0.01},\"adjacent\":[323,418]}",
"418": "{\"pos\":[16,8],\"type\":23,\"size\":\"Small\",\"name\":\"Speed\",\"description\":[\"+0.01 speed\"],\"modifiers\":{\"speed\":0.01},\"adjacent\":[417,423]}",
"419": "{\"pos\":[18,7],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[276,420]}",
"420": "{\"pos\":[18,8],\"type\":19,\"size\":\"Small\",\"name\":\"Luck\",\"description\":[\"+0.05 luck\"],\"modifiers\":{\"luck\":0.05},\"adjacent\":[419,421]}",
"421": "{\"pos\":[18,9],\"type\":316,\"size\":\"Med\",\"name\":\"First Item Luck\",\"description\":[\"+0.07 luck when first obtaining a passive item.\"],\"modifiers\":{\"firstItemLuck\":0.07},\"adjacent\":[420]}",
"423": "{\"pos\":[16,9],\"type\":314,\"size\":\"Med\",\"name\":\"First Item Speed\",\"description\":[\"+0.01 speed when first obtaining a passive item.\"],\"modifiers\":{\"firstItemSpeed\":0.01},\"adjacent\":[418]}",
"424": "{\"pos\":[17,-9],\"type\":313,\"size\":\"Med\",\"name\":\"First Item Range\",\"description\":[\"+0.03 range when first obtaining a passive item.\"],\"modifiers\":{\"firstItemRange\":0.03},\"adjacent\":[414]}",
"425": "{\"pos\":[14,9],\"type\":312,\"size\":\"Med\",\"name\":\"First Item Tears\",\"description\":[\"+0.03 tears when first obtaining a passive item.\"],\"modifiers\":{\"firstItemTears\":0.03},\"adjacent\":[416]}",
"426": "{\"pos\":[13,-9],\"type\":311,\"size\":\"Med\",\"name\":\"First Item Damage\",\"description\":[\"+0.03 damage when first obtaining a passive item.\"],\"modifiers\":{\"firstItemDamage\":0.03},\"adjacent\":[410]}",
"428": "{\"pos\":[4,9],\"type\":310,\"size\":\"Small\",\"name\":\"Tinted Rock All Stats\",\"description\":[\"+0.01 all stats when blowing up a tinted rock.\"],\"modifiers\":{\"tintedRockAllstats\":0.01},\"adjacent\":[406]}",
"429": "{\"pos\":[8,3],\"type\":310,\"size\":\"Small\",\"name\":\"Tinted Rock All Stats\",\"description\":[\"+0.01 all stats when blowing up a tinted rock.\"],\"modifiers\":{\"tintedRockAllstats\":0.01},\"adjacent\":[405]}",
"431": "{\"pos\":[20,0],\"type\":302,\"size\":\"Small\",\"name\":\"Secret Room Floor Luck\",\"description\":[\"+0.1 luck for the current floor when first entering a secret or super secret room.\"],\"modifiers\":{\"secretRoomFloorLuck\":0.1},\"adjacent\":[278]}",
"434": "{\"pos\":[-23,-8],\"type\":42,\"size\":\"Med\",\"name\":\"Grab Bags\",\"description\":[\"+0.25% chance to spawn a grab-bag when collecting a pickup\"],\"modifiers\":{\"grabBag\":0.25},\"adjacent\":[378]}",
"443": "{\"pos\":[15,-9],\"type\":315,\"size\":\"Med\",\"name\":\"First Item Shot Speed\",\"description\":[\"+0.03 shot speed when first obtaining a passive item.\"],\"modifiers\":{\"firstItemShotspeed\":0.03},\"adjacent\":[412]}",
"444": "{\"pos\":[19,-1],\"type\":317,\"size\":\"Small\",\"name\":\"Less Shot Speed\",\"description\":[\"-0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":-0.02},\"adjacent\":[279,445]}",
"445": "{\"pos\":[19,-2],\"type\":317,\"size\":\"Small\",\"name\":\"Less Shot Speed\",\"description\":[\"-0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":-0.02},\"adjacent\":[444,446]}",
"446": "{\"pos\":[19,-3],\"type\":317,\"size\":\"Small\",\"name\":\"Less Shot Speed\",\"description\":[\"-0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":-0.02},\"adjacent\":[445,447]}",
"447": "{\"pos\":[19,-4],\"type\":317,\"size\":\"Small\",\"name\":\"Less Shot Speed\",\"description\":[\"-0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":-0.02},\"adjacent\":[446,448]}",
"448": "{\"pos\":[19,-5],\"type\":317,\"size\":\"Small\",\"name\":\"Less Shot Speed\",\"description\":[\"-0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":-0.02},\"adjacent\":[447,451]}",
"449": "{\"pos\":[19,-7],\"type\":317,\"size\":\"Small\",\"name\":\"Less Shot Speed\",\"description\":[\"-0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":-0.02},\"adjacent\":[451,450]}",
"450": "{\"pos\":[19,-8],\"type\":317,\"size\":\"Small\",\"name\":\"Less Shot Speed\",\"description\":[\"-0.02 shot speed\"],\"modifiers\":{\"shotSpeed\":-0.02},\"adjacent\":[449,452]}",
"451": "{\"pos\":[19,-6],\"type\":318,\"size\":\"Med\",\"name\":\"Less Shot Speed\",\"description\":[\"-0.08 shot speed\"],\"modifiers\":{\"shotSpeed\":-0.08},\"adjacent\":[448,449]}",
"452": "{\"pos\":[19,-9],\"type\":318,\"size\":\"Med\",\"name\":\"Less Shot Speed\",\"description\":[\"-0.08 shot speed\"],\"modifiers\":{\"shotSpeed\":-0.08},\"adjacent\":[450]}"
}
]])