function PST:getChangelogList()
    local changelog = {
        "(You can disable this popup on new versions through Mod Config Menu Pure in-game)",
        "",

        "v0.4.21",
        "- Hush flies are no longer affected by HP modifiers. This also fixes their initial invulnerability not being applied.",
        "",

        "v0.4.20",
        "- Added support for many Fiend Folio monsters and bosses, such as stopping certain monsters from duplicating,",
        "becoming champions or gaining HP.",
        "- Added a node to the global tree that informs you if the save backups addon is not detected. This node is",
        "purely informative and goes away once the addon is installed.",
        "- Expedition reset obol cost now caps out at 500.",
        "",

        "v0.4.19",
        "- Epiphany: Added support for various feature interactions, such as chests, familiars, mobs, items, etc.",
        "- Epiphany: Sidereal Caches can now be opened with Multitools.",
        "- Epiphany: Fixed Tarnished Judas' phase transitions removing xp and levels.",
        "- Crimson Starcores can now show up at expedition depths 15+ (from 20+), at a slightly reduced rate.",
        "- Added a new Ancient astral weapon: Metamorphic Claw (gauntlet).",
        "- Added a new global node that allows switching the tree description box style freely.",
        "- Marked now contributes to 'while firing' modifiers at a reduced rate, while the marker is out.",
        "- Opening the tree now disables the 'Filter' game option while open, as it breaks some sprites.",
        "- Keeper and T. Keeper can no longer receive broken hearts from expedition effects.",
        "- Fixed Starsteel Broadaxe error when updating its buff.",
        "",

        "v0.4.18",
        "- Added xp and leveling support for Epiphany's Tarnished characters.",
        "- Epiphany: Tarnished Keeper no longer turns special pickups from this mod into coins, such as jewels, weapons,",
        "caches or obols.",
        "- Fixed Delirium re-initializing when switching forms.",
        "",

        "v0.4.17",
        "- Introduced Crimson Starcores, a new character-bound material that can sometimes show up as a reward",
        "in depth 20+ expeditions' final nodes.",
        "- Once obtained, Crimson Starcores enable new Crimson Nodes within character trees, which allow selecting",
        "medium nodes from other trees to be applied to that character.",
        "- Added help pages explaining Crimson Starcores & Nodes, under the Expeditions category.",
        "- Introduced a new astral weapon type: Gauntlets. Comes with 2 ancients: Magefist and Ironhand.",
        "- Introduced a new astral weapon type: Great Maces. Comes with 5 ancients: Mighty Purifier, Chaotic Tumult,",
        "Firestarter, Colossal Maul and Tolling Bell.",
        "- Added a new Ancient astral weapon: Ivory Vampire (dagger).",
        "- Devil deal expedition objectives now also count purchasing items with coins while in the devil room,",
        "rather than just hearts.",
        "- Opening Sidereal Caches in challenge rooms should now start the challenge.",
        "- Fixed general monster modifiers (such as higher hp or speed) not applying to monsters spawned after",
        "entering the room.",
        "- Fixed T. Azazel's \"Curseborne\" node affecting friendly monsters.",
        "- Fixed Auric Persecutor calculating the tears multiplier incorrectly.",
        "- Fixed Starsteel Broadaxe's buff persisting between rooms. Its maximum tear buff is now 33% (from 40%).",
        "",

        "v0.4.16",
        "- Added a 'Press Q' hint message to the global tree UI for accessing the current character's tree.",
        "- Adjusted mod update logic priority to avoid conflicts with certain older mods.",
        "- Fixed Ancient Weapon modifier upgrades going past the maximum value for certain weapons.",
        "- Fixed Astral Forge weapon modifications occasionally not getting saved.",
        "- Fixed Myosotis being able to spawn un-openable Sidereal Caches.",
        "",

        "v0.4.15",
        "- Fixed Ancient Weapon Bounties being able to award weapon tiers above 5, which causes errors.",
        "",

        "v0.4.14",
        "- Added a new Ancient Jewel: \"Shiftstone\".",
        "- XP multiplier setting can now go up to 5.0.",
        "- Ancient Weapon Bounties' weapon rewards now have their tier determined by the highest expedition depth",
        "you've reached.",
        "- Fixed Ancient Essence counter when deconstructing weapons (it was displaying the same number as the",
        "sparkling essence counter).",
        "",

        "v0.4.13",
        "- Added an internal versioning system for expedition generation. Saved expeditions should still work",
        "as before, but new expeditions generated from this version onwards will use the latest generator version.",
        "This should help prevent issues where expeditions unintentionally re-roll node types, rewards, curses, etc.",
        "- Introduced a new Sidereal Tree large node in the Astral Forge area: Ancient Weapon Bounties.",
        "This allows you to spend obols to generate a 'bounty', a group of objectives to complete that rewards you",
        "with an ancient weapon of the chosen type.",
        "- Timeless Bazaar items no longer cost global SP, and have had their obol costs adjusted.",
        "- Purchased Timeless Bazaar items are no longer removed when starting a run (they will still be removed by",
        "the bazaar refreshing naturally when winning / losing twice).",
        "- Added a help screen to the Astral Forge category explaining astral weapon tiers.",
        "- Adjusted Judas' \"Sacrifice Darkness\", it now removes the gained black heart, grants a soul heart, and",
        "triggers Necronomicon's effect, instead of just trying to damage you. It can now trigger in the mirror",
        "dimension.",
        "- Fixed challenges that apply tree mods using the last menu-selected character's tree instead of the",
        "challenge character's tree.",
        "- Fixed special chests that drop items not counting towards chest expedition objectives.",
        "- Fixed ancient weapon imprinting not checking for material costs.",
        "- Potential fix for Timeless Bazaar checking the wrong cost internally, making purchases fail occasionally.",
        "- Fixed T. Blue Baby's small poop upgrade nodes re-triggering when entering visited rooms.",
        "",

        "v0.4.12",
        "- Adjusted how expeditions save and load boons/curses, preventing issues like boons occasionally not",
        "being applied to runs.",
        "- Adjusted Eldritch Mapping: it can now trigger up to 3 times per floor, reduces all stats by -4% per trigger",
        "(from -6%) and adds +10% curse chance to the next floor (from +15%).",
        "- Ultra sin bosses (pre-beast) no longer drop ancient stardust.",
        "- Glowing Glass Piece (ancient jewel) no longer attempts to trigger in boss rooms.",
        "- Fixed certain Sidereal Tree nodes being allocatable with 0 global SP.",
        "",

        "v0.4.11",
        "- Potential fix for Bazaar items costing the wrong amount internally, making the purchase fail.",
        "- Fixed basement 1 during the Ascent counting as entering the first floor and triggering associated effects.",
        "- Fixed Sidereal Universalization node not being applied properly.",
        "",

        "v0.4.10",
        "- Added a new Ancient astral weapon: Circuit Splitter (axe).",
        "- Generally reduced Timeless Bazaar's item and refreshing costs.",
        "- Added the ability to 'freeze/unfreeze' offered items in the Timeless Bazaar. This prevents the offered items",
        "from getting re-rolled naturally by winning/losing runs, allowing you to save them for a later run.",
        "- Added a help screen describing this item freezing feature to the timeless bazaar help section.",
        "- Fixed occasional error when using certain active items.",
        "- Fixed T. Jacob's \"Spiritual Covenant\" working even while Jacob wasn't in spirit form.",
        "",

        "v0.4.9",
        "- Fixed Sidereal Tree modifiers not being applied to runs under certain circumstances.",
        "",

        "v0.4.8",
        "- Added a new Ancient astral weapon: Glowing Sunblade (longsword).",
        "- Adjusted starmight requirement for expeditions, it now grows slower with depth and caps at 800.",
        "- Fixed Glowing Moonblade (ancient weapon) having no effects.",
        "",

        "v0.4.7",
        "- Added tooltip to global nodes that don't support dynamic tree mode, as these can only be applied on run start.",
        "- Fixed issue where Boss Rush and Blue Womb timer modifiers could be applied incorrectly.",
        "",

        "v0.4.6",
        "- Added a hint to hovered weapons in the Astral Forge displaying the 'equip' keybind, and updated controls help screen.",
        "- Adjusted drop rate of magic and ancient astral weapons, generally making these more frequent finds.",
        "",

        "v0.4.5",
        "- Added a new Ancient Jewel: \"Glittering Starstone\".",
        "- Adjusted Sidereal Caches' internal ID to potentially avoid conflicts.",
        "- Expeditions' Curse of Punishment damage should no longer cause penalties such as reducing devil deal chance.",
        "- Fixed Lost Coral Trident (ancient weapon) not being registered when picked up.",
        "- Fixed final expedition nodes occasionally being replaced by different node types.",
        "- Fixed cases where completing the last node in an expedition wouldn't reset it and unlock the next depth.",
        "- Fixed chests that give items when opened not counting towards expedition objectives.",
        "- Fixed stone chests not counting towards expedition objectives.",
        "",

        "v0.4.4",
        "- Slightly adjusted obol drop rates within runs. Boss obol drops now slightly decrease the chance for further boss",
        "obol drops within that run.",
        "- Increased Sidereal Cache spawning nodes' chances.",
        "- The circular slash's damage from the Scythe weapon implicit mod is now capped at 4x your current damage stat.",
        "",

        "v0.4.3",
        "- Added new '1px beam' drawing styles for the xp bar, and xp related options are now under their own category on",
        "Mod Config Menu.",
        "- Changelog screen now allows panning horizontally, in case text overflows in certain screen sizes.",
        "- Nodes that require global SP to allocate now say so in their description while unallocated.",
        "- Potential fix for modded active items not triggering the 'Use active items with at least 3 charges' expedition",
        "objective.",
        "- Fixed boss rush completion rewards being able to trigger again when killing more monsters after clearing it.",
        "- Fixed inventory sub-menus (such as starcursed jewel inventories) staying open when switching tree screens.",
        "",

        "v0.4.2",
        "- Fixed Timeless Bazaar selected item description boxes. These now work for modded items and should no longer",
        "be able to overflow the screen.",
        "- Fixed boss room clear effects triggering again when re-entering and killing normal monsters in the room.",
        "- Fixed boss rush wave modifiers applying multiple times to the total wave count when starting multiple new runs",
        "with them allocated.",
        "",

        "v0.4.1",
        "- Fixed champion chest drops being guaranteed with any champion kill.",
        "",

        "v0.4.0",
        "- Introduced two new main features found within the Star Tree: the Arcane Astrolabe and the Sidereal Tree.",
        "You can find more info about these in the tree's help panels or in the mod's workshop description.",
        "- New 'Dynamic Tree Mode' global node that allows applying the tree's node changes in real time to runs.",
        "- Added multiple new node types to the global tree.",
        "- Changed character level up sound to avoid confusion with angel rooms.",
        "- XP gain in challenges is now tied to the \"Apply tree in challenges\" option.",
        "- Adjusted trinket gilding global nodes. This effect now only rolls once per unique trinket type per run.",
        "- Judas' \"Sacrifice Darkness\" can no longer trigger in the mirror dimension, and the self damage should",
        "- no longer be able to kill you at any point.",
        "- Reworked T. Isaac's \"Consuming Void\" large node.",
        "- Split T. Judas' \"Dark Expertise\" node into two large nodes, making the How to Jump effect optional. You",
        "might need to re-allocate these.",
        "- T. Siren's \"Acrid Gaze\" pulse now fires slightly in front of you, instead of right at your position.",
        "- Fixed T. Keeper's \"Blessed Pennies\" effect being guaranteed unconditionally when entering a shop.",
        "- Fixed Embered Azurite (ancient jewel) not applying its debuff after leaving a run.",
        "",

        "v0.3.24",
        "- Added option to lower the drawn XP bar scale/size.",
        "- Added option to disable Starcursed Jewel drops. You can disable all drops, or just jewels for which your",
        "inventory is full.",
        "- Isaac's \"Intermittent Conceptions\" should now only remove Birthright on a room's first visit.",
        "- Refactored Cain's \"Impromptu Gambler\", and it should now properly work as described. It now draws items",
        "from the Treasure, Shop, Devil, Angel or Crane Game item pools randomly, and consumes 2 additional coins",
        "on use (from 3).",
        "- Fixed Cain's \"Impromptu Gambler\" occasionally draining additional coins multiple times per use.",
        "- Fixed secondary characters (such as Esau) not getting their stats updated by certain effects.",
        "- Fixed Starcursed Jewel drops being able to be gilded by the Golden Trinkets nodes, preventing collection.",
        "- Fixed \"Pickup Scarcity\" modifiers being able to remove existing pickups when re-entering rooms.",
        "- Fixed troll bomb disarming modifiers being able to disarm existing troll bombs when re-entering rooms.",
        "",

        "v0.3.23",
        "- Refactored the entirety of the tree rendering code, in preparation for future features.",
        "It should all work the same as before, but let me know if issues pop up.",
        "- Reworked the help screen (opened with H / Select) to provide additional info about the mod's",
        "features. More info will be added to this screen as new features emerge.",
        "- Added an option to use a different style for tree node description boxes, which might look better",
        "in fullscreen or small resolutions.",
        "- Modified Golden Trinket nodes. Now these grant \"When first grabbing a trinket, % chance to turn",
        "it into its golden version.\".",
        "",
    }

    for idx, tmpLine in ipairs(changelog) do
        if type(tmpLine) == "string" and tmpLine == PST.modVersion then
            ---@diagnostic disable-next-line: assign-type-mismatch
            changelog[idx] = {tmpLine .. " (Current)", KColor(0.7, 1, 0.9, 1)}
        end
    end
    return changelog
end