function PST:getChangelogList()
    local changelog = {
        "(You can disable this popup on new versions through Mod Config Menu Pure in-game)",
        "",

        "v1.2.7",
        "- Added a new Ancient Jewel: \"Labyrinth Stone\".",
        "- The \"Cursed Auric Shard\" ancient jewel now stops triggering its effect after clearing the floor's boss room.",
        "- Fixed obols not dropping when clearing challenge rooms or the boss rush in non-expedition runs with Sidereal Universalization",
        "allocated.",
        "- Fixed expeditions not getting reset when switching savefiles if their depth wasn't reached on the new savefile. This could cause",
        "newly reached depths to have in-progress expeditions from a different savefile.",
        "- Fixed Ancient Jewel xp bonus not being applied properly when equipped.",
        "",

        "v1.2.6",
        "- XP penalty for clearing the same room multiple times no longer applies in Greed mode.",
        "- Fixed Deep-Space Distortion modifier that limits pickups unintentionally affecting keys based on coin quantity.",
        "",

        "v1.2.5",
        "- Internal support for Astral Vessel 0.2.5 functionality.",
        "- Added 2 new Ancient weapons: Divine Interceptor (longsword) and Divine Messenger (bow).",
        "",

        "v1.2.4",
        "- Added support for items/entities from the Rebekah mod.",
        "- CHAOSMODE.",
        "",

        "v1.2.3",
        "- Clearing the same room multiple times now applies a stacking xp penalty to that room (such as Community Remix's hexed rooms).",
        "- Refactored code logic for room clears, should generally cause less jank in cases where monsters spawn on cleared rooms.",
        "- Reduced Shadowmeld's cooldown to 7 seconds (from 12) (Siren tree).",
        "- Shadowmeld now has quality 1 and EID description, in case it ever needs to show up as an item.",
        "",

        "v1.2.2",
        "- Beta for Astral Vessel, a new customizable character based on PST, is now public! Check it out in the workshop.",
        "- You can now queue expedition nodes following a selected node. When completing an objective within a run, if",
        "there are queued nodes, the current node will get automatically completed and the next node in the queue gets selected.",
        "Final node won't get automatically completed and will still require manual completion, as it resets the expedition.",
        "- Fixed expeditions being able to roll Boon rewards in the final node.",
        "- Fixed expedition Curse of Urgency applying the wrong time internally.",
        "",

        "v1.2.1",
        "- Internal support for addition of functions when closing tree screen or submenus (needed for future compat).",
        "",

        "v1.2.0",
        "- Added support for items/entities for the following mods: (thanks wookywok!)",
        "Restored Collection, Rune Rooms, Preyn's Collections (Cursed, Quarry, Golden, Rotten, Sewage, Toybox).",
        "- Added support for Community Remix's Insane difficulty (counts as hard difficulty for completion and xp purposes).",
        "- Certain on-hit effects now have an internal cooldown, including Sword of Song and Apollyon's Locust Tears nodes.",
        "- Adjusted expedition mods (also affects ubers):",
        "    - Expedition length now increases by 1 every 5 depths (from 3), up to a max of 9 nodes (from 15).",
        "    - Implicit HP mods for monsters and bosses are now split, and are generally lower.",
        "    - Implicit pickup scarcity mod is now capped at 25% (from 33%).",
        "    - Implicit damage reduction mod now only applies to bosses.",
        "    - HP modifiers are 50% as effective on the first floor, and 75% as effective on the second floor.",
        "- Adjusted uber expeditions (most of these will only apply to newly generated ones):",
        "    - Implicit mod strength is now increased every 40 entropy (from 24), up to 8 times (from 10).",
        "    - An Expedition Curse is now added every 60 entropy (from 30).",
        "    - Deep-Space Distortion modifiers are now added every 75 entropy (from 50).",
        "    - Uber length now starts at 5, increases to 6 at depths 3+, and 7 at depths 6+.",
        "    - Deep-Space skill points are now granted every 2 nodes (from 3).",
        "    - Deep-Space Distortion modifier adjustments:",
        "        - +30% final boss damage reduction (from 40%).",
        "        - You cannot have more than 35 coins, 8 keys or 8 bombs (from 25, 4, 4).",
        "        - +33% heart scarcity (from 50%).",
        "        - +33% coin, key and bomb scarcity (from 50%).",
        "- Reworked expedition reset costs. Normal expeditions cost up to 100 obols and 30 respecs, while ubers cost",
        "200 obols and 70+ respecs.",
        "- Judas' Inner Demon node no longer has Dark Judas start with 1 black heart, and applies -45% damage as",
        "Dark Judas (from -35%).",
        "- Optimized the player cache update function, which should improve general performance somewhat.",
        "- Old chest conversion global nodes can no longer trigger in the Chest/Dark Room floors.",
        "- Potential fix for rare crash on run start.",
        "- Fixed error when using the 'luamod' command while in-game and having Epiphany installed (Tr. Judas check).",
        "- Fixed inputs propagating to the menu while the tree screen is open. This can fix issues such as unintentionally",
        "changing the difficulty with the Difficulty Library mod.",
        "",

        "v1.1.14",
        "- Internal node drawing additions for mod compatibility.",
        "",

        "v1.1.13",
        "- Compatibility for locusts and blue items from the 'Malware & Spam' mod (thanks wookywok!).",
        "- Fixed Embered Azurite not generating blue items from compatible mods.",
        "",

        "v1.1.12",
        "- Added a large node to the sidereal tree: 'Obol Magnetism', which makes obol pickups move towards you.",
        "- Fixed error when starting a run using Ironhand (ancient gauntlet weapon) with no honing.",
        "",

        "v1.1.11",
        "- Added support for items/entities for the following mods: (thanks wookywok!)",
        "Heaven's Call mod, latest D!Edith update, More Penny Trinkets, Sewing Machine, Bael.",
        "- Added support for mod items that grant extra lives, for relevant effects.",
        "- Added Deep-Space Tree nodes that allow you to additionally grant a portion of obols picked up to",
        "all other characters, at a reduced rate.",
        "- Added 2 new global node types: 'Old Chest Conversion' and 'Scared Heart Conversion'.",
        "- Added a large global node: 'Unclick'.",
        "- Deep-Space Astrolabe node now requires completing expedition depth 12 (from 15), allowing access to Uber",
        "Expeditions a bit earlier.",
        "- Fixed Uber Expedition distortion modifier 'Tree stats are % less effective' causing base character stats to",
        "plummet as well.",
        "",

        "v1.1.10",
        "- Fixed error whenever obols dropped in Uber Expeditions without entropy.",
        "",

        "v1.1.9",
        "- Scarcity modifiers no longer apply during the mineshaft sequence.",
        "- Reworked the effect of Expeditions' Curse of Power Demand.",
        "- Fixed Uber Expeditions dropping low tier weapons.",
        "- Fixed Uber Expeditions applying some curses with lower modifiers.",
        "",

        "v1.1.8",
        "- Added an in-game warning when the sudden death on final boss Uber Expedition mod becomes active.",
        "- Further fix attempt for error when claiming Uber Expedition nodes that reward order.",
        "",

        "v1.1.7",
        "- Added compatibility for items/entities from the following mods: (thanks wookywok!)",
        "Lost and Forgotten, Reshaken Vol. 1, Tainted Treasure Rooms.",
        "- Fixed Ctrl + Allocate not working for the Astral Forge's Multi-Deconstruction mode.",
        "",

        "v1.1.6",
        "- You can now favorite weapons in the Astral Forge menu. Press Shift + H while hovering a weapon to favorite it.",
        "Favorited weapons cannot be deconstructed and have a sun icon at the bottom left.",
        "- Added a favorite weapon filter to the Astral Forge.",
        "- Weapon stats now remain displayed while in the Astral Forge's deconstruction mode.",
        "- Monsters blacklisted from getting health modifiers no longer receive damage reduction mods either.",
        "- Internal support for easier addition of special node descriptions and requirements, particularly for other mods.",
        "- Fix error when first completing Uber Expedition nodes that grant Order.",
        "",

        "v1.1.5",
        "- Fixed effects involving Ultra Secret rooms not triggering, such as Bloodmoon Meridion.",
        "- Fixed Luck stat calculation.",
        "",

        "v1.1.4",
        "- Adjusted some expedition implicit modifiers, such as monster HP % and damage reduction, particularly at",
        "greater depths (15+).",
        "- Adjusted 'expedition enabled/disabled' text display.",
        "- Cosmic Realignment now requires less nodes to reach.",
        "",

        "v1.1.3",
        "- Adjusted T. Siren's Chromatic Dissonance effect.",
        "- Fixed T. Siren's Chromatic Dissonance being able to reroll into the same obtained familiar.",
        "",

        "v1.1.2",
        "- Fixed % tear modifiers being inverted on stat update.",
        "",

        "v1.1.1",
        "- Potential fix for Uber Expeditions internally loading incorrectly when first generated.",
        "",

        "v1.1.0",
        "- Introduced Uber Expeditions, a more difficult version of astral expeditions with their own set of rewards.",
        "You can begin these by allocating the 'Deep-Space Astrolabe' in the Star Tree, and pressing the uber toggle",
        "button in the Astrolabe menu.",
        "- Introduced the 'Deep-Space Skill Tree', a set of nodes in the Star Tree that use Deep-Space skill points,",
        "obtainable from Uber Expeditions.",
        "- Introduced Starblessed Prisms, a new resource that allows you to 'Starbless' an Ancient Weapon. Starblessed",
        "weapons can have an additional modifier imprinted into them. You can apply these in the Astral Forge.",
        "- Introduced the 'Obscure Bazaar', present in the Deep-Space Skill Tree, which allows you to exchange large",
        "amounts of obols for unique items, such as Crimson Starcores or Starblessed Prisms.",
        "- Expedition \"Curse of Shrouding\" no longer affects final nodes.",
        "- Starmight requirement for expeditions is now capped at 600 (from 800).",
        "- Added a new large node to T. Siren: \"Chromatic Dissonance\".",
        "- Additional compatibility for various items/entities from the following mods: (thanks wookywok!)",
        "Kicks and Giggles, Eclipsed.",
        "- Fixed jewel champion-turning modifier still affecting blacklisted mod enemies.",
        "- Fixed heart scarcity jewel modifier not being applied properly.",
        "- Fixed Respec logic sometimes preventing valid nodes from being respecced.",
        "- Fixed The Forgotten's \"% melee damage per bone item\" nodes not being applied.",
        "",

        "v1.0.3",
        "- Added a new Septentrional Artifact to the Sidereal Tree: Superstitious Septentrion.",
        "- Added a new Meridional Artifact to the Sidereal Tree: Bloodmoon Meridion.",
        "- Additional compatibility for items/entities of the following mods: (thanks wookywok!)",
        "Siren (character), Andromeda, Samael, Bertran, Mastema, D!Edith, Red Baby, Sheriff, Duke, Martha of Bethany, Arachna.",
        "- Adjusted Timeless Bazaar refresh button info when spent for the current cycle.",
        "- Fixed error on update for Tarnished Judas (Epiphany).",
        "- Fixed Magefist (gauntlet) ancient weapon upgrading.",
        "",

        "v1.0.2",
        "- Added a new Meridional Artifact to the Sidereal Tree: Snake-Eye Meridion.",
        "- Added Whips as a selectable weapon type for Ancient Weapon Bounties.",
        "- Added support for various items, entities and interactions for the following mods: (thanks wookywok!)",
        "Epiphany, Fiend Folio, Repentance Plus! (mod), Reverie, Revelations, Community Remix, Retribution, Reverie MGO,",
        "and THE FUTURE.",
        "- Magic Septentrion now generates 4 energy per used item charge (from 2).",
        "- Fixed effects that conditionally grant you passive items triggering repeatedly during the mineshaft chase sequence.",
        "- Fixed 'Special Sacks' nodes making shop sacks free.",
        "- Fixed Snakebite ancient weapon upgrading.",
        "- Fixed Mulligan occasionally being given to any character when hit (from Keeper's 'Blue Kin' node).",
        "",

        "v1.0.1",
        "- Added a \"Multi-Deconstruction\" button to the Astral Forge, which allows you to select multiple weapons before",
        "deconstructing them at once. Also allows selecting all currently filtered weapons.",
        "- Added honing filter buttons to the Astral Forge.",
        "- Fixed \"Eve's Mascara\" nodes not removing the item when entering a new room.",
        "",

        "v1.0.0",
        "- No longer BETA status (really it was mostly figurative, updates may still come in the future).",
        "- Added support for Community Remix items.",
        "- Added 2 new Ancient Jewels: Blazing Carnelian and Cat's-Eye Prism.",
        "- Added a new large node in Eden's tree that allows you to freely pick a hairstyle to apply to the runs.",
        "- Many vanilla character trees have received either a few new nodes and large nodes, or a bigger rework.",
        "Check the mod description page for a link to specific changes.",
        "- Introduced a new astral weapon type: Whips. Comes with 4 ancients: Snakebite, Devil's Tongue, Azurebinder",
        "and Sacred Scourge.",
        "- New Sidereal Tree feature: Sidereal Artifacts. These allow choosing between many artifact nodes that grant a",
        "condition to generate 'energy', and an effect to be triggered once enough energy is gathered.",
        "- New Sidereal Tree node: Crimson Convergence. Once allocated, it allows selecting one of many buffs that grow",
        "stronger the more Crimson Starcores your character owns.",
        "- Crimson nodes can now be respecced, and doing so will return the spent Crimson Starcores.",
        "- Expedition item rewards now draw items from a fixed pool, regardless of item unlock status. This also means",
        "mod items can no longer appear as rewards, given potential inconsistencies if enabling/disabling more/existing mods.",
        "Unfortunately this means that existing item reward nodes will get rerolled one last time.",
        "- The following effects now trigger only on monster hits, instead of any hit such as self damage:",
        "Fickle Fortune (Cain node), Flimsy Gadgets expedition curse, +% speed when hit mod, Cosmic Realignment curses,",
        "Martian Ultimatum and Crimson Warpstone ancient jewels.",
        "- Bosses can no longer be turned into champions with tree/jewel effects.",
        "- Increased the cooldown between Nimble Twins (ancient quickblade) tear shots.",
        "- Eve's Bird Foot familiars should now trigger effects related to Dead Bird.",
        "- Adjusted how Sidereal Tree weapon type drop nodes are checked, and should now be more effective.",
        "- Fixed error when first loading a savefile while having Epiphany.",
        "- Fixed Cause Converter incorrectly spawning Chub and variants.",
        "- Fixed Mistlestone turning progression items into mystery gifts.",
        "- Potential fix for Storm's Advance weapon occasionally causing self damage.",
        "",

        "v0.4.27",
        "- Additional compatibility for the latest Epiphany version.",
        "- Crimson nodes can no longer be respecced.",
        "- Sidereal tree: replaced a set of sidereal cache key consumption nodes with a new set of nodes:",
        "\"% chance for Sidereal Caches to return 1-2 keys when opened\"",
        "- Global tree: reduced total chance for \"Sacrifice Room Red Hearts\" nodes (42% -> 25%).",
        "- Segmented bosses should now count only once per type per room for expedition objectives.",
        "- Rooms no longer trigger on-clear effects if there are submerged enemies waiting to show up.",
        "- Reduced xp gained from destroying frozen enemies.",
        "- Destroying frozen enemies should no longer proc effects that spawn more enemies.",
        "- Phantasm Prism (ancient jewel) now triggers up to 12 times per room.",
        "- Scared red hearts are now accounted for in pickup effects, such as The Lost's \"Heartseeker Phantasm\".",
        "- Can now imprint modifiers into ancient weapons using magic gauntlets with 3 modifiers.",
        "- Added warning text to the Ancient Weapon Bounties screen for non-expedition runs (can't progress objectives).",
        "- Adjusted many expedition objective checks to work for bounties if Sidereal Universalization is allocated.",
        "- Controllers can now press RT to open the quick access menu within the tree screen.",
        "- Fixed Select not opening help menu on controllers.",
        "- Fixed \"Meek Giants\" expedition boon applying to non-boss monsters.",
        "- Fixed Lazarus' \"A True Ending?\" being able to drop multiple Suicide King cards in a single room.",
        "- Fixed error and data initialization for Tarnished Judas (Epiphany).",
        "- Fixed first phase of Mega Satan counting as a final boss, instead of only second phase.",
        "- Fixed sub-menus (such as jewel inventories) staying open when switching menus.",
        "- Fixed expedition Curse of the Heartbroken not applying broken hearts properly.",
        "- Fixed config keybinds getting overwritten by save data.",
        "",
    }

    for idx, tmpLine in ipairs(changelog) do
        if type(tmpLine) == "string" and tmpLine == PST.modVersion then
            ---@diagnostic disable-next-line: assign-type-mismatch
            changelog[idx] = {tmpLine .. " (Current)", KColor(0.7, 1, 0.9, 1)}
        end
    end
    return changelog
end